name = "personacore-website"
compatibility_date = "2024-10-23"
pages_build_output_dir = "."
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[env.production]
compatibility_flags = ["nodejs_compat"]
